kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: gw
spec:
  gatewayClassName: gloo-gateway
  listeners:
    - protocol: HTTP
      port: 8080
      name: http
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
spec:
  parentRefs:
    - name: gw
  hostnames:
    - "example.com"
  rules:
    - backendRefs:
        - name: aws-upstream
          kind: Upstream
          group: gloo.solo.io
          filters:
            - type: ExtensionRef
              extensionRef:
                group: gloo.solo.io
                kind: Parameter
                name: uppercase
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: aws-upstream
spec:
  aws:
    region: us-east-1
    roleArn: arn:aws:iam::123456789012:role/lambda-role
    lambdaFunctions:
      - lambdaFunctionName: uppercase
        logicalName: uppercase