name: Docs Issue
description: Fix our docs or add new information
labels: ["Type: Docs"]
body:
  - type: markdown
    attributes:
      value: |
        **Note**: This is a public repo. Be sure to obscure or redact any sensitive information.
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of the Gloo Edge docs does this affect?
      options:
        - main (1.16.x beta)
        - 1.15.x (latest)
        - 1.14.x
        - 1.13.x 
        - 1.12.x
    validations:
      required: true
  - type: textarea
    id: change-details
    attributes:
      label: Describe the requested changes
      description: List the desired changes to be made to the Gloo Edge docs
  - type: textarea
    id: docs-links
    attributes:
      label: Link to any relevant existing docs
      placeholder: |
        1. https://docs.solo.io/gloo-edge/latest...
        2. ...
  - type: textarea
    id: browser-details
    attributes:
      label: Browser Information
      description:
        If the change isn't related to content, please include your browser version and any other relevant information 
        (e.g., browser zoom) to help us reproduce docs-related bugs
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, links to related issues or PRs, etc. about the docs request here
