{{- if .Values.kubeGateway.enabled -}}
{{- $labels := include "gloo-gateway.constLabels" . | fromYaml }}
{{- $labels = merge $labels (include "gloo-gateway.labels" . | fromYaml) }}
{{- $data := fromYaml (.Files.Get "files/rbac/role.yaml") -}}
{{- $newName := printf "%s.%s" $data.metadata.name  .Release.Namespace -}}
{{- $data = mergeOverwrite $data (dict "metadata" (dict "name" $newName)) -}}
{{- $data = mergeOverwrite $data (dict "metadata" (dict "labels" $labels)) -}}
{{ toYaml $data }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gloo-gateway.fullname" . }}.{{.Release.Namespace}}
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
    {{- include "gloo-gateway.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "gateway.networking.k8s.io"
  resources:
  - gatewayclasses
  - gateways
  - tcproutes
  - httproutes
  - referencegrants
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - nodes
  - secrets
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "gateway.solo.io"
  resources:
  - routeoptions
  - virtualhostoptions
  - listeneroptions
  - httplisteneroptions
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "gateway.networking.k8s.io"
  resources:
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  - tcproutes/status
  verbs: ["update", "patch"]
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
    {{- include "gloo-gateway.labels" . | nindent 4 }}
  name: {{ include "gloo-gateway.fullname" . }}.{{.Release.Namespace}}-binding
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gloo-gateway.fullname" . }}.{{.Release.Namespace}}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gloo-gateway.fullname" . }}-deploy.{{.Release.Namespace}}
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
    {{- include "gloo-gateway.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "gateway.gloo.solo.io"
  resources:
  - gatewayparameters
  - directresponses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - services
  - serviceaccounts
  - configmaps
  verbs: ["get", "list", "watch", "patch", "create"]
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs: ["get", "list", "watch", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
    {{- include "gloo-gateway.labels" . | nindent 4 }}
  name: {{ include "gloo-gateway.fullname" . }}-deploy.{{.Release.Namespace}}-binding
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gloo-gateway.fullname" . }}-deploy.{{.Release.Namespace}}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "gloo-gateway.constLabels" . | nindent 4 }}
    {{- include "gloo-gateway.labels" . | nindent 4 }}
  name: {{ include "gloo-gateway.fullname" . }}-k8s.{{.Release.Namespace}}-binding
subjects:
- kind: ServiceAccount
  name: gloo
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: k8sgw-controller.{{.Release.Namespace}}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
