{{- if .Values.gateway.rolloutJob.enabled }}
{{- if .Values.global.glooRbac.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-rollout{{ include "gloo.rbacNameSuffix" . }}
  labels:
    app: gloo
    gloo: rbac
rules:
- apiGroups: ["gateway.solo.io"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "patch"]
{{- end -}}{{/* if .Values.global.glooRbac.create */}}
{{- end }}{{/* if .Values.gateway.rolloutJob.enabled  */}}
