{{- if .Values.gateway.cleanupJob.enabled }}
{{- if .Values.global.glooRbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0" # must be created before cleanup job
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  name: gloo-resource-cleanup
  namespace: {{ .Release.Namespace }}
{{- end }}{{/* if .Values.global.glooRbac.create */}}
{{- end }}{{/* if .Values.gateway.cleanupJob.enabled  */}}
