{{- if .Values.gateway.rolloutJob.enabled }}
{{- $image := .Values.gateway.rolloutJob.image }}
{{- if .Values.global }}
{{- $image = merge .Values.gateway.rolloutJob.image .Values.global.image }}
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gloo
    gloo: resource-rollout
  name: gloo-resource-rollout-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "5" # run this job after the role/rolebinding is created
    {{- include "gloo.jobHelmDeletePolicySucceededAndBeforeCreation" .Values.gateway.rolloutJob | nindent 4 }}
spec:
  {{- include "gloo.jobSpecStandardFields" .Values.gateway.rolloutJob | nindent 2 -}}
  template:
    metadata:
      labels:
        gloo: resource-rollout
        sidecar.istio.io/inject: "false"
        {{- if .Values.gateway.rolloutJob.extraPodLabels }}
        {{- range $key, $value := .Values.gateway.rolloutJob.extraPodLabels }}
        {{ $key | quote }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- if or .Values.settings.linkerd .Values.gateway.rolloutJob.extraPodAnnotations }}
      annotations:
        {{- if .Values.settings.linkerd }}
        "linkerd.io/inject": disabled
        {{- end }}
        {{- range $key, $value := .Values.gateway.rolloutJob.extraPodAnnotations }}
        {{ $key | quote }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- include "gloo.pullSecret" $image | nindent 6 -}}
      serviceAccountName: gloo-resource-rollout-cleanup
      {{- include "gloo.podSpecStandardFields" .Values.gateway.rolloutJob | nindent 6 -}}
      containers:
        - name: kubectl
          image: {{template "gloo.image" $image}}
          imagePullPolicy: {{ $image.pullPolicy }}
          securityContext:
            {{- if .Values.gateway.rolloutJob.readOnlyRootFilesystem }}
            readOnlyRootFilesystem: {{ .Values.gateway.rolloutJob.readOnlyRootFilesystem }}
            {{- end }}
            runAsNonRoot: true
            {{- if not .Values.gateway.rolloutJob.floatingUserId }}
            runAsUser: {{ printf "%.0f" (float64 .Values.gateway.rolloutJob.runAsUser) -}}
            {{- end }}
          {{- with .Values.gateway.rolloutJob.resources }}
          resources: {{ toYaml . | nindent 12}}
          {{- end }}
          command:
          - /bin/sh
          - -c
          - |
            # Check if the resource rollout job exists
            kubectl -n {{ .Release.Namespace }} get job gloo-resource-rollout &> /dev/null
            if [ $? -eq 0 ]
            then
              echo "Cleaning up resource-rollout-job"
              # Clean it up so it doesn't cause issues with upgrades
              kubectl -n {{ .Release.Namespace }} delete job gloo-resource-rollout || exit $?
            fi
{{- if .Values.global.glooRbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: rbac
  name: gloo-resource-rollout-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight":  "0"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-rollout-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight":  "0"
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-rollout-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight":  "0"
roleRef:
  kind: Role
  name: gloo-resource-rollout-cleanup
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gloo-resource-rollout-cleanup
  namespace: {{ .Release.Namespace }}
{{- end }}{{/* if .Values.global.glooRbac.create */}}
{{- end }}{{/* if .Values.gateway.rolloutJob.enabled  */}}