name: Conformance Tests
description: run kubernetes gateway api conformance tests
runs:
  using: "composite"
  steps:
  - name: Prep Go Runner
    uses: ./.github/workflows/composite-actions/prep-go-runner
  - name: Install kind
    uses: helm/kind-action@v1.10.0
    with:
      install_only: true
      version: ${{ matrix.kube-version.kind }}
  - uses: azure/setup-kubectl@v4
    id: kubectl
    with:
      version: ${{ matrix.kube-version.kubectl }}
  - uses: azure/setup-helm@v4
    with:
      version: ${{ matrix.kube-version.helm }}
  - name: Setup test env
    shell: bash
    env:
      CLUSTER_NODE_VERSION: ${{ matrix.kube-version.node }}
      IMAGE_VARIANT: ${{ matrix.image-variant }}
      CONFORMANCE: "true"
    run: ./ci/kind/setup-kind.sh
  - name: Install Gloo Gateway Enterprise with k8s gateway integration enabled
    shell: bash
    run: |
      helm upgrade -i -n gloo-system gloo ./_test/gloo-1.0.0-ci1.tgz --create-namespace \
        --set kubeGateway.enabled=true \
        --set global.image.variant=${{ matrix.image-variant }}
  - name: Run kubernetes gateway api conformance tests
    shell: bash
    run: make conformance
  - name: print events
    if: ${{ failure() }}
    shell: bash
    run: kubectl -n gloo-system  get events --sort-by='{.lastTimestamp}'
