changelog:
  - type: DEPENDENCY_BUMP
    dependencyOwner: solo-io
    dependencyRepo: protoc-gen-openapi
    dependencyTag: v0.2.2
    description: >-
      "Update protoc-gen-openapi to v0.2.2. This includes capability to specify additional schema constraints for CRDs such as CEL rules and OpenAPI schema constraints (minimum, maximum, default, etc.)"
