name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Check for DO_NOT_SUBMIT
        run: ./ci/do-not-submit.sh ${{ steps.changed-files.outputs.all_modified_files }}
