name: Push API Changes to solo-apis
on:
  release:
    types: [published]
  # This job has flaked on releases. We enable manually triggering the workflow
  # so that developers do not need to run this step manually when a flake occurs
  workflow_dispatch:
    inputs:
      release-tag-name:
        description: 'Release Tag Name'
        required: true
        default: ''
      release-branch:
        description: 'Release Branch'
        required: true
        default: ''
jobs:
  prepare-env:
    name: Prepare Environment Variables
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      # The tag for the release commit (ie v1.8.0)
      release-tag-name: ${{ steps.release-tag-name.outputs.value }}

      # The LTS branch that was released (ie v1.8.x)
      release-branch: ${{ steps.release-branch.outputs.value }}

      # The prefix used to differentiate LTS branches in solo-apis
      solo-apis-prefix: 'gloo'
    steps:
    - id: release-tag-name
      run: |
        RELEASE_TAG_NAME=${{ github.event.inputs.release-tag-name }}
        if [[ ${{ github.event_name == 'release' }} = true ]]; then
          RELEASE_TAG_NAME=${{ github.event.release.tag_name }}
        fi
        echo "value=$RELEASE_TAG_NAME" >> $GITHUB_OUTPUT
    - id: release-branch
      run: |
        RELEASE_BRANCH=${{ github.event.inputs.release-branch }}
        if [[ ${{ github.event_name == 'release' }} = true ]]; then
          RELEASE_BRANCH=${{ github.event.release.target_commitish }}
        fi
        echo "value=$RELEASE_BRANCH" >> $GITHUB_OUTPUT
  push-to-solo-apis-branch:
    needs: prepare-env
    env:
      RELEASE_TAG_NAME: ${{ needs.prepare-env.outputs.release-tag-name }}
      RELEASE_BRANCH: ${{ needs.prepare-env.outputs.release-branch }}
      SOLO_APIS_PREFIX: ${{ needs.prepare-env.outputs.solo-apis-prefix }}
    name: Publish Gloo APIs
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Free disk space
        run: |
          echo "Before clearing disk space:"
          df -h

          # https://github.com/actions/virtual-environments/issues/709
          sudo apt-get clean

          # Clean up pre-installed tools
          # https://github.com/actions/virtual-environments/issues/1918
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf $AGENT_TOOLSDIRECTORY

          echo "After clearing disk space:"
          df -h
      - name: Install SSH Deploy key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SOLO_API_DEPLOY_KEY }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          repository: solo-io/gloo
          path: gloo
          ref: ${{ env.RELEASE_TAG_NAME }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
           go-version-file: gloo/go.mod
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          repository: solo-io/solo-apis
          path: solo-apis
          # Checkout the solo-apis LTS branch that tracks the Gloo LTS branch
          # NOTE: This will fail if the solo-apis LTS branch does not exist.
          ref: '${{env.SOLO_APIS_PREFIX}}-${{ env.RELEASE_BRANCH }}'
      - name: Update solo-apis
        env:
          # The LTS branch in solo-apis that will hold the published apis (ie gloo-v1.8.x)
          SOLO_APIS_DESTINATION_BRANCH: '${{env.SOLO_APIS_PREFIX}}-${{ env.RELEASE_BRANCH }}'
          # The branch that this GHA will commit to.
          # The branch name fits the following shape: sync-apis/${SOLO_API_LTS_BRANCH}/${SOLO_APIS_TAG_NAME}
          # Using this structure, the solo-apis repo can run actions to generate pull requests to the proper LTS branch
          # and tag those branches after they merge.
          # For example, releasing v1.8.0 will create a pull request:
          #   gloo-v1.8.x <-- sync-apis/gloo-v1.8.x/gloo-v1.8.0
          SOLO_APIS_SOURCE_BRANCH: 'sync-apis/${{ env.SOLO_APIS_PREFIX }}-${{ env.RELEASE_BRANCH }}/${{ env.SOLO_APIS_PREFIX }}-${{ env.RELEASE_TAG_NAME }}'
          GIT_USER_NAME: soloio-bot
          GIT_USER_EMAIL: soloio-bot@github.com
        run: |
          cd solo-apis
          make mod-download update-deps; ./hack/sync-gloo-apis.sh; make generate
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git add .
          git checkout -B $SOLO_APIS_SOURCE_BRANCH
          git commit -m "Sync Gloo APIs. Destination Branch: $SOLO_APIS_DESTINATION_BRANCH" --allow-empty
          git remote add solo-apis git@github.com:solo-io/solo-apis.git
          git push solo-apis $SOLO_APIS_SOURCE_BRANCH