changelog:
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/gloo/issues/10145
    resolvesIssue: false
    description: >-
      Updated the datadog tracer config proto to match envoy v1.31. New fields include
      `collector_hostname` and `remote_config`. Remote config can now be configured or 
      disabled completely. 
  - type: DEPENDENCY_BUMP
    dependencyOwner: solo-io
    dependencyRepo: envoy-gloo
    dependencyTag: 1.31.2-patch1
    description: >-
      Bump envoy-gloo to upgrade to envoy v1.31.2
